In [7]:
import model
import tensorflow as tf
import importlib
importlib.reload(model)

<module 'model' from '/Users/hanshen/work/grpo_demo/model.py'>

In [8]:
a = tf.constant([
    [[0.1, 0.1, 0.2, 0.2, 0.3, 0.3], [0.1, 0.1, 0.2, 0.2, 0.3, 0.3]]
])

In [9]:
a

<tf.Tensor: shape=(1, 2, 6), dtype=float32, numpy=
array([[[0.1, 0.1, 0.2, 0.2, 0.3, 0.3],
        [0.1, 0.1, 0.2, 0.2, 0.3, 0.3]]], dtype=float32)>

In [10]:
mha = model.MHA(3, 6)


In [11]:
mha.build()

In [12]:
mha(a)

<tf.Tensor: shape=(1, 2, 6), dtype=float32, numpy=
array([[[-1.5682538e-04,  3.1109592e-03,  2.7328837e-03, -1.9444246e-04,
         -7.0705952e-05,  6.5764273e-03],
        [-1.5682538e-04,  3.1109592e-03,  2.7328837e-03, -1.9444246e-04,
         -7.0705952e-05,  6.5764273e-03]]], dtype=float32)>